name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_APP_NAME: cloud-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true

    - name: Authenticate Docker
      run: |
        gcloud auth configure-docker ${{ env.GKE_ZONE }}-docker.pkg.dev --quiet

    - name: Build and Push Docker image
      run: |
        IMAGE=${{ env.GKE_ZONE }}-docker.pkg.dev/${{ env.GKE_PROJECT }}/cloud-app/${{ env.GKE_APP_NAME }}:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Deploy to GKE
      run: |
        envsubst < k8s/Service.yml | kubectl apply -f -
        envsubst < k8s/Deployment.yml | kubectl apply -f -
